
project_id = "jqpivqdwblrccjzicnxn"

[api]
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions]
[functions.invite-user]
verify_jwt = true

[functions.discord-notify]
verify_jwt = true

[functions.discord-create-event]
verify_jwt = true

[functions.contact-form]
verify_jwt = true

[functions.calendar-sync]
verify_jwt = false

[functions.rss-feed]
verify_jwt = false
