
CREATE TABLE public.support_committee (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    first_name text NOT NULL,
    last_name text NOT NULL,
    email text NOT NULL,
    city text,
    subscribed_to_newsletter boolean NOT NULL DEFAULT false,
    CONSTRAINT support_committee_pkey PRIMARY KEY (id),
    CONSTRAINT support_committee_email_key UNIQUE (email)
);

ALTER TABLE public.support_committee ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable public read access"
ON public.support_committee
FOR SELECT
USING (true);

CREATE POLICY "Enable insert for anyone"
ON public.support_committee
FOR INSERT
WITH CHECK (true);

-- Add the table to the publication for replication
ALTER PUBLICATION supabase_realtime ADD TABLE public.support_committee;
