
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jqpivqdwblrccjzicnxn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpxcGl2cWR3YmxyY2NqemljbnhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3MDc0OTcsImV4cCI6MjA1NzI4MzQ5N30.DqU__7FqUW45Mu96gdJbuLjuAEjI4CMEQW95Z3Cg92o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Helper type for news_categories table since it might not be in the auto-generated types
export type NewsCategory = {
  id: string;
  name: string;
  created_at?: string;
};

// Helper type for projects
export type { Project } from '@/types/projects.types';

// Helper type for committees
export type Committee = {
  id: string;
  title: string;
  description: string;
  icon: string;
  team_photo_url?: string | null;
  cover_photo_url?: string | null;
  color: string | null;
  created_at?: string;
  updated_at?: string;
};

export type CommitteeWork = {
  id: string;
  title: string;
  content: string;
  date: string;
  committee_id: string;
  created_at: string;
  images: string[] | null; // Mise à jour pour correspondre au type attendu
  files: string[] | null; // Mise à jour pour correspondre au type attendu
};

// Helper type for program_general
export type ProgramGeneral = {
  id: string;
  content: string;
  created_at: string;
  updated_at: string;
};

// Type assertion helper for Supabase queries
export function asTable<T>(tableName: string): string {
  return tableName;
}
