
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jqpivqdwblrccjzicnxn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpxcGl2cWR3YmxyY2NqemljbnhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3MDc0OTcsImV4cCI6MjA1NzI4MzQ5N30.DqU__7FqUW45Mu96gdJbuLjuAEjI4CMEQW95Z3Cg92o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Helper type for news_categories table since it might not be in the auto-generated types
export type NewsCategory = {
  id: string;
  name: string;
  created_at?: string;
};

// Helper type for news articles with category relation
export type NewsArticleWithCategory = {
  id: string;
  title: string;
  excerpt: string;
  content: string;
  category?: string;
  category_id?: string;
  category_name?: string;
  date: string;
  image: string;
  tags: string[];
  status: string;
  author_id?: string;
  publication_date?: string;
  comments_enabled?: boolean;
};
